accounts/urls.py
from django.urls import path
from .views import login_view, logout_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

eyup_sultan_moschee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hauptseite.urls')),
    path('fuehrung/', include('fuehrung.urls')),
    path('gemeinde/', include('gemeinde.urls')),
    path('mitgliedsantrag/', include('mitgliedsantrag.urls')),
    path('downloads/', include('downloads.urls')),
    path('accounts/', include('accounts.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path("kalender/", include("kalender.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hauptseite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.startseite, name='startseite'),
    path('neuigkeit-hinzufuegen/', views.neuigkeit_hinzufuegen, name='neuigkeit_hinzufuegen'),
    path('kontakt/', views.kontakt_view, name='kontakt'),
    path('kontakt/danke/', views.kontakt_danke, name='kontakt_danke'),
     path('neuigkeit/<int:pk>/', views.neuigkeit_detail, name='neuigkeit_detail'),
     path('impressum/', views.impressum, name='impressum'),
]

hauptseite/models.py
from django.db import models
from django.utils import timezone

class Neuigkeit(models.Model):
    titel = models.CharField(max_length=200)
    inhalt = models.TextField()
    bild = models.ImageField(upload_to='neuigkeiten_bilder/', blank=True, null=True)
    erstellt_am = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.titel

class KontaktNachricht(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    nachricht = models.TextField()
    erstellt_am = models.DateTimeField(auto_now_add=True)
    bearbeitet = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} ({self.email}) - {self.erstellt_am.strftime('%Y-%m-%d %H:%M')}"

hauptseite/forms.py
from django import forms
from .models import KontaktNachricht

class KontaktForm(forms.ModelForm):
    class Meta:
        model = KontaktNachricht
        fields = ['name', 'email', 'nachricht']
        widgets = {
            'nachricht': forms.Textarea(attrs={'rows': 5}),
        }

hauptseite/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Neuigkeit
from django.http import JsonResponse
from .forms import KontaktForm
from django.contrib import messages
from django.utils import timezone
from kalender.models import Event
from datetime import timedelta

def startseite(request):
    # Neuigkeiten laden
    neuigkeiten = Neuigkeit.objects.all().order_by('-erstellt_am')[:5]

    # Kalender-Logik
    heute = timezone.localdate()
    start_param = request.GET.get('start')

    if start_param:
        try:
            wochenstart = timezone.datetime.strptime(start_param, "%Y-%m-%d").date()
        except ValueError:
            wochenstart = heute - timedelta(days=heute.weekday())
    else:
        wochenstart = heute - timedelta(days=heute.weekday())

    wochenende = wochenstart + timedelta(days=6)
    events = Event.objects.filter(date__range=[wochenstart, wochenende]).order_by('date', 'start_time')
    wochentage = [wochenstart + timedelta(days=i) for i in range(7)]
    prev_week = wochenstart - timedelta(days=7)
    next_week = wochenstart + timedelta(days=7)

    context = {
        "neuigkeiten": neuigkeiten,
        "wochenstart": wochenstart,
        "wochenende": wochenende,
        "wochentage": wochentage,
        "events": events,
        "prev_week": prev_week,
        "next_week": next_week,
    }

    # Wichtig: richtiger Template-Pfad!
    return render(request, "hauptseite/startseite.html", context)

def neuigkeit_hinzufuegen(request):
    if request.method == 'POST':
        titel = request.POST.get('titel')
        inhalt = request.POST.get('inhalt')
        bild = request.FILES.get('bild')  # Bild kann optional sein

        neuigkeit = Neuigkeit(titel=titel, inhalt=inhalt)
        if bild:
            neuigkeit.bild = bild
        neuigkeit.save()

        return JsonResponse({'status': 'success'})
    return JsonResponse({'status': 'error'})

def neuigkeit_detail(request, pk):
    neuigkeit = get_object_or_404(Neuigkeit, pk=pk)
    return render(request, 'hauptseite/neuigkeit_detail.html', {'neuigkeit': neuigkeit})

def kontakt_view(request):
    if request.method == 'POST':
        form = KontaktForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('kontakt_danke')
    else:
        form = KontaktForm()
    return render(request, 'hauptseite/kontakt.html', {'form': form})

def kontakt_danke(request):
    return render(request, 'hauptseite/kontakt_danke.html')

def impressum(request):
    return render(request, 'hauptseite/impressum.html')

templates/hauptseite/impressum.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Impressum{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/impressum.css' %}">
{% endblock %}


{% block content %}
<div class="impressum-container">
    <h1>Impressum</h1>
    <section class="statischer-bereich">
        <p>
            <b>DITIB-Türkisch Islamische Gemeinde zu Gersthofen e.V.</b>
            <br>
                Gründungsjahr: 1986
            <br>
            <hr>
                1245.vorstand@ditib-by-s.de
            <br>    
                Amtsgericht Augsburg VR-1362
            <br>    
                Finanzamt Augsburg-Land 
            <br>    
                Steuernummer.:102/111/10029
        </p>
        </section>
    
    <!-- Hier kannst du deine Impressum-Daten einfügen -->
</div>
{% endblock %}

templates/hauptseite/kontakt.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="fuehrung-form-container">
  <h2>Kontakt</h2>
  <p>Sie haben Fragen oder möchten mit uns in Kontakt treten? Schreiben Sie uns gern.</p>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
  {% endif %}

  <form method="POST" class="kontakt-form">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-field">
        <label for="id_name">Name:</label>
        {{ form.name }}
        </div>
        
        <div class="form-field">
        <label for="id_email">E-Mail:</label>
        {{ form.email }}
        </div>

        <div class="form-field">
            <label for="id_nachricht">Nachricht:</label>
            {{ form.nachricht }}
        </div>
       
        <div class="form-submit">
          <button type="submit" class="kontakt-button">Absenden</button>
        </div>
    </div>
    
    
  </form>
      
</div>      
      
  
<div class="fuehrung-form-container">
  <div class="kontakt-info">
    <h2>Adresse & Anfahrt</h2>
    <p>
      Eyüp Sultan Moschee Gersthofen<br>
      Ausgburgerstraße 120<br>
      86368 Gersthofen<br>
      E-Mail: info@eyup-sultan.de<br>
      Tel: 0821 / 123456
    </p>
    </div>
    <br>
    <div class="kontakt-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50391.7111793203!2d10.839541449909055!3d48.41069339229038!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479ebdae27a523a7%3A0xed86874319bed6a6!2sDITIB%20Ey%C3%BCp%20Sultan%20Moschee%20Gersthofen!5e0!3m2!1sde!2sde!4v1746723425719!5m2!1sde!2sde" 
            width="100%" height="300"
            style="border:0;" allowfullscreen=""
            loading="lazy" referrerpolicy="no-referrer-when-downgrade">
        </iframe>
    </div>
  </div>

{% endblock %}

templates/hauptseite/kontakt_danke.html
{% extends 'base.html' %}

{% block content %}
<div class="danke-wrapper">
  <h2>Vielen Dank für Ihre Nachricht!</h2>
  <p>Vielen Dank für Ihre Nachricht. Wir melden uns schnellstmöglich bei Ihnen.</p>
</div>
{% endblock %}

templates/hauptseite/startseite.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/startseite.css' %}">
  <link rel="stylesheet" href="{% static 'css/kalender.css' %}">
{% endblock %}

{% block content %}
<div class="startseite-content">

<!-- HERO-BEREICH -->
<section class="startseite-hero">
  <div class="startseite-hero-content">
    <h1>Willkommen in der Eyüp Sultan Moschee Gersthofen</h1>
    <p>Unsere Moschee steht für Gemeinschaft, Frieden und spirituelles Wachstum.</p>
    <a href="https://www.paypal.com/de/home" class="startseite-cta-button">Jetzt spenden</a>
  </div>
  <div class="startseite-hero-image">
    <img src="{% static 'images/hero.png' %}" alt="Eyüp Sultan Moschee Gersthofen">
  </div>
</section>



 <!-- ZEITSTRAHL -->
<section class="startseite-timeline">
  <h2>Unsere Geschichte</h2>
  <div class="timeline-container">
    <div class="timeline-item">
      <div class="timeline-img">
        <img src="{% static 'images/timeline1.jpg' %}" alt="1986">
      </div>
      <div class="timeline-content">
        <h3>1986</h3>
        <p>Vereinsgründung, Bauerstr. Gersthofen</p>
      </div>
    </div>
    <div class="timeline-item">
      <div class="timeline-img">
        <img src="{% static 'images/timeline2.jpg' %}" alt="1995">
      </div>
      <div class="timeline-content">
        <h3>1995</h3>
        <p>Neue Vereinsstätte mit Erwerb eines Grundstücks</p>
      </div>
    </div>
    <div class="timeline-item">
      <div class="timeline-img">
        <img src="{% static 'images/timeline3.jpg' %}" alt="2006">
      </div>
      <div class="timeline-content">
        <h3>2006</h3>
        <p>Neubau der Moschee</p>
      </div>
    </div>
    <div class="timeline-item">
      <div class="timeline-img">
        <img src="{% static 'images/timeline4.jpg' %}" alt="2018">
      </div>
      <div class="timeline-content">
        <h3>2018</h3>
        <p>Neubau der Bildungsstätte</p>
      </div>
    </div>
    <div class="timeline-item">
      <div class="timeline-img">
        <img src="{% static 'images/timeline5.jpg' %}" alt="Heute">
      </div>
      <div class="timeline-content">
        <h3>Heute</h3>
        <p>Wachsende Gemeinde mit über 400 Mitgliedern</p>
      </div>
    </div>
  </div>
</section>




<!-- NEUIGKEITEN-BEREICH -->
<section class="startseite-blog">
  <h2>Neuigkeiten</h2>
  <div class="startseite-blog-slider">
    {% for neuigkeit in neuigkeiten %}
      <div class="startseite-blog-card">
        {% if neuigkeit.bild %}
          <img src="{{ neuigkeit.bild.url }}" alt="{{ neuigkeit.titel }}">
        {% endif %}
        <h3>{{ neuigkeit.titel }}</h3>
        <p>{{ neuigkeit.inhalt|truncatewords:15}}</p>
        
      </div>
    {% empty %}
      <p>Keine Neuigkeiten vorhanden.</p>
    {% endfor %}
  </div>
</section>


<section class="kalender-container">
  <h2>Kalender – Diese Woche</h2>

  

  <div class="kalender-grid">
    {% for datum in wochentage %}
      <div class="tag">
        <strong>{{ datum|date:"l" }}<br>{{ datum|date:"d.m.Y" }}</strong>
        {% for event in events %}
          {% if event.date == datum %}
            <div class="event">
              <strong>{{ event.title }}</strong>
              {% if event.start_time %}{{ event.start_time|time:"H:i" }}{% endif %}
              {% if event.end_time %} – {{ event.end_time|time:"H:i" }}{% endif %}
              {% if event.description %}<p>{{ event.description }}</p>{% endif %}
            </div>
          {% endif %}
        {% endfor %}
      </div>
    {% endfor %}
  </div>
</section>




<!-- KURSE -->
<section class="startseite-kurse">
  <h2>Kurse</h2>
  <ul>
    <li>Kindermoschee (Kindergartenalter)</li>
    <li>Kuran- und Islamunterrichtskurs</li>
    <li>Kuran lesen für Erwachsene und Jugendliche</li>
    <li>Makam Kurse für Jugendliche</li>
    <li>Hafız Unterricht für Jugendliche</li>
    <li>Arabisch Kurs für Männer</li>
    <li>Reue Programm</li>
  </ul>
  <p class="startseite-spendenhinweis">Bitte beachten Sie, dass bei einer Anmeldung zu den Kursen der Kinder am Wochenende eine Spende von mindestens 10 Euro gewünscht ist.</p>
</section>

<!-- JUGENDGRUPPEN -->
<section class="startseite-jugendgruppen">
  <h2>Jugendgruppen</h2>
  <p>Die Jugendgruppen finden regelmäßige Treffen am Freitag zu einem islamischen Vortrag statt. Außerhalb der Treffen veranstaltet unser Jugendvorstand Grillen, Hallenspiele und Reisen.</p>
  <a href="https://www.instagram.com/ditib_jugend_gersthofen/" target="_blank">Instagram</a>
  <a href="https://www.youtube.com/@DitibJugendGersthofen" target="_blank">YouTube</a>
</section>

<!-- YOUTUBE VIDEO -->
<section class="video-section">
    <h2 class="section-title">Aktuelles Video</h2>
    <div class="video-wrapper">
      <iframe 
        src="https://www.youtube.com/embed/ADteIh6lako" 
        title="Aktuelles Video"
        frameborder="0" 
        allowfullscreen
      ></iframe>
    </div>
  </section>


</div>
{% endblock %}